controllers/CardController.php
<?php
/**
 * Created by PhpStorm.
 * User: A
 * Date: 05.02.18
 * Time: 20:31
 */

namespace app\controllers;

use app\models\Card;
use app\models\Product;
use Yii;
use yii\web\Session;
use app\models\Order;
use app\models\OrderItem;


class CardController extends AppController
{

    public function actionAdd()
    {
        $this->layout = false;
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        $product = Product::find()->where(['id' => $id])->one();
        if (empty($product)) {
            return false;
        }
        $session = Yii::$app->session;
        $session->open();
        $card = new Card();
        $card->addToCard($product, $qty);
        if (!Yii::$app->request->isAjax) {
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('card-model', compact('session'));

    }

    public function actionClearCard()
    {
        $this->layout = false;
        $session = Yii::$app->session;
        $session->open();
        $session->remove('card');
        $session->remove('card.qty');
        $session->remove('card.sum');
        $this->layout = false;
        return $this->render('card-model', compact('session'));
    }

    public function actionDelItem()
    {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $card = new Card();
        $card->recalc($id);
        $this->layout = false;
        return $this->render('card-model', compact('session'));
    }

    public function actionShow()
    {
        $this->layout = false;
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('card-model', compact('session'));
    }

    public function actionView()
    {
        $this->setMeta('Корзина');
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if ($order->load(Yii::$app->request->post())) {
            $order->qty = $session['card.qty'];
            $order->sum = $session['card.sum'];
            if ($order->save()) {
                $this->saveOrderItems($session['card'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят. Менеджер вскоре свяжется с вами');
                Yii::$app->mailer->compose('order', compact('session'))
                    ->setFrom(['antonovsasha22@gmail.com' => 'eshop'])
                    ->setTo($order->email)
                    ->setSubject('Заказ')
                    ->send();
                $session->remove('card');
                $session->remove('card.qty');
                $session->remove('card.sum');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'Ваш заказ принят. Менеджер вскоре свяжется с вами');
            }
        }
        return $this->render('view', compact('session', 'order'));
    }

    protected function saveOrderItems($items, $order_id) {
            foreach ($items as $id => $item) {
                $order_items = new OrderItem();
                $order_items->order_id = $order_id;
                $order_items->product_id = $id;
                $order_items->name = $item['name'];
                $order_items->price = $item['price'];
                $order_items->qty_item = $item['qty'];
                $order_items->sum_item = $item['price'] * $item['qty'];
                if (!$order_items->save()) {
                    $arr[] = $order_items->getErrors();
                }
            }
    }
}

controllers/CategoryController.php
<?php
/**
 * Created by PhpStorm.
 * User: A
 * Date: 16.01.18
 * Time: 21:23
 */

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;
use yii\web\HttpException;

class CategoryController extends AppController
{
    public function actionIndex()
    {
        $hits = Product::find()->where(['hit' => 1])->limit(6)->all();
        $sales = Product::find()->where(['sale' => 1])->limit(6)->all();
        $this->setMeta('E-SHOPPER');
        return $this->render('index', compact('hits', 'sales'));
    }

    public function actionView()
    {
        $id = Yii::$app->request->get('id');
        $category = Category::findOne($id);
        if (empty($category)) {
            throw new HttpException(404, 'Такой категории нет');
        };
        $category = Category::findOne($id);
        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination([
            'totalCount' => $query->count(),
            'pageSize' => 6,
            'pageSizeParam' => false,
            'forcePageParam' => false
        ]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        $this->setMeta('E-SHOPPER | ' . $category->name, $category->keywords, $category->description);
        return $this->render('view', compact('products', 'pages', 'category'));
    }

    public function actionSearch()
    {
        $q = trim(Yii::$app->request->get('q'));
        if (!$q) {
            return $this->render('search', compact('q'));
        }
        $this->setMeta('E-SHOPPER | Поиск' . $q);
        $query = Product::find()->where(['like', 'name', $q]);
        $pages = new Pagination([
            'totalCount' => $query->count(),
            'pageSize' => 3,
            'pageSizeParam' => false,
            'forcePageParam' => false
        ]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('search', compact('products', 'pages', 'q'));
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Product;
use app\models\RegistrationForm;
use app\models\UserIdentity;
use Yii;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->redirect('/category/index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionRegistration()
    {
        $model = new RegistrationForm();
        if ($model->load(Yii::$app->request->post()) && $model->registration(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('registrationSuccess', 'На вашу почту отправленно письмо с дальнейшими инструкциями');
            return $this->refresh();
        }
        return $this->render('registration', compact('model'));
    }

    public function actionActivate($accessToken)
    {
        $model = UserIdentity::findIdentityByAccessToken($accessToken);
        if ($model) {
            $model->access_token = null;
            $model->is_activated = 1;
            if ($model->save() && Yii::$app->user->login($model)) {
                Yii::$app->session->setFlash('activateSuccess', 'Поздравляем! Вы зарегистрировались на сайте');
            }
        }
        return $this->render('activate');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\assets\LtAppAsset;

AppAsset::register($this);
LtAppAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Home | E-Shopper</title>
        <link rel="shortcut icon" href="images/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
    </head><!--/head-->

    <body>
    <?php $this->beginBody() ?>
    <header id="header"><!--header-->
        <div class="header_top"><!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="tel:+2-95-01-88-821"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                                <li><a href="mailto:info@webraccoon.pro"><i class="fa fa-envelope"></i> info@webraccoon.pro</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-vk"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->
        <div class="header-middle"><!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 col-xs-12">
                        <div class="logo">
                            <a href="<?= \yii\helpers\Url::home() ?>"><?= Html::img('@web/images/home/logo.png', ['alt' => 'logo']) ?></a>
                        </div>
                    </div>
                    <div class="col-sm-8 col-xs-12">
                        <div class="shop-menu">
                            <ul class="nav navbar-nav pull-right">
                                <li><a href="#" onclick="return getCard()"><i
                                                class="fa fa-shopping-cart"></i>Корзина</a>
                                </li>
                                <?php if (!Yii::$app->user->isGuest) : ?>
                                    <li><a href="<?= \yii\helpers\Url::to(['/site/logout']) ?>"><i
                                                    class="fa fa-user"></i><?= Yii::$app->user->identity->username ?>
                                            (Выйти)</a></li>
                                <?php else : ?>
<!--                                    <li><a href="#"><i class="fa fa-star"></i> Избранное</a></li>-->
                                    <li><a href="<?= \yii\helpers\Url::to('/site/login') ?>"><i
                                                    class="fa fa-lock"></i>
                                            Вход</a></li>
                                    <li><a href="<?= \yii\helpers\Url::to('/site/registration') ?>"><i
                                                    class="fa fa-user""></i>
                                            Регистрация</a></li>
                                <?php endif; ?>
                            </ul>
                            <div class="search_box pull-right">
                                <form method="get" action="<? \yii\helpers\Url::to(['category/search']) ?>">
                                    <input type="text" placeholder="Search" name="q"/>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </header><!--/header-->

    <?= $content ?>

    <footer id="footer"><!--Footer-->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2017.</p>
                    <p class="pull-right">Created by <span><a target="_blank"
                                                              href="https://webraccoon.pro">Webraccoon</a></span>
                    </p>
                </div>
            </div>
        </div>
    </footer><!--/Footer-->

    <?php
    \yii\bootstrap\Modal::begin([
        'header' => '<h2>Корзина</h2>',
        'id' => 'card',
        'size' => 'modal-lg',
        'footer' => '<button type="button" class="btn btn-default" data-dismiss= modal>Продолжить покупки</button>
        <a href="' . \yii\helpers\Url::to(['card/view']) . '" class="btn btn-success">Оформить заказ</a>
        <button type="button" class="btn btn-danger" onclick="clearCard()">Очистить корзину</button>'

    ]);
    \yii\bootstrap\Modal::end();
    ?>
    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>